spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 30000  # 30 seconds
        response-timeout: 120000  # 2 minutes
      discovery:
        locator:
          enabled: true  # Deshabilitamos el discovery locator automático
      routes:
        # Crop Service
        - id: crop-service
          uri: lb://CROP-SERVICE
          predicates:
            - Path=/api/v1/crops/**
          filters:
            - name: CircuitBreaker
              args:
                name: crop-service-circuit-breaker
                fallbackUri: forward:/fallback/service-unavailable
        
        # Treatment Service
        - id: treatment-service
          uri: lb://TREATMENT-SERVICE
          predicates:
            - Path=/api/v1/treatments/**
          filters:
            - name: CircuitBreaker
              args:
                name: treatment-service-circuit-breaker
                fallbackUri: forward:/fallback/service-unavailable
        
        # User Service
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**, /api/v1/farmers/**, /api/v1/auth/**, /api/v1/roles/**
          filters:
            - name: CircuitBreaker
              args:
                name: user-service-circuit-breaker
                fallbackUri: forward:/fallback/service-unavailable
        
        # Notification Service
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - name: CircuitBreaker
              args:
                name: notification-service-circuit-breaker
                fallbackUri: forward:/fallback/service-unavailable
        
        # Report Service
        - id: report-service
          uri: lb://REPORT-SERVICE
          predicates:
            - Path=/api/v1/reports/**
          filters:
            - name: CircuitBreaker
              args:
                name: report-service-circuit-breaker
                fallbackUri: forward:/fallback/service-unavailable
        
        # Subscription Service
        - id: subscription-service
          uri: lb://SUBSCRIPTION-SERVICE
          predicates:
            - Path=/api/v1/subscriptions/**
          filters:
            - name: CircuitBreaker
              args:
                name: subscription-service-circuit-breaker
                fallbackUri: forward:/fallback/service-unavailable
        
        # Payment Gateway Service
        - id: payment-gateway-service
          uri: lb://HIDROGREEN-PAYMENT-GATEWAY-SERVICE
          predicates:
            - Path=/api/v1/payments/**
          filters:
            - name: CircuitBreaker
              args:
                name: payment-service-circuit-breaker

        - id: detection-diagnose-post
          uri: lb://detection-service
          predicates:
            - Path=/api/v1/detections/diagnose
            - Method=POST
          filters:
            - name: CircuitBreaker
              args:
                name: detection-diagnose-circuit-breaker
                fallbackUri: forward:/fallback/service-unavailable
                timeout: 600000

        # Ruta general para otros endpoints
        - id: detection-diagnose-service
          uri: lb://detection-service
          predicates:
            - Path=/api/v1/detections/**
            - Method=GET,PUT,DELETE
          filters:
            - name: Ci  rcuitBreaker
              args:
                name: detection-diagnose-circuit-breaker
                fallbackUri: forward:/fallback/service-unavailable
                timeout: 600000
                
    loadbalancer:
      ribbon:
        enabled: false
      cache:
        enabled: false
      health-check:
        enabled: true
        interval: 25s

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://discovery-service:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    eureka-server-connect-timeout-seconds: 10
    eureka-server-read-timeout-seconds: 10
    initial-instance-info-replication-interval-seconds: 5
    instance-info-replication-interval-seconds: 10
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:api-gateway}
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 30  # Aumentado de 10
    lease-expiration-duration-in-seconds: 90  # Aumentado

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,routes,circuitbreakers
  endpoint:
    gateway:
      access: UNRESTRICTED
    health:
      show-details: always

logging:
  level:
    "[org.springframework.cloud.gateway]": DEBUG
    "[org.springframework.cloud.loadbalancer]": DEBUG
    "[com.netflix.discovery]": DEBUG
    "[com.netflix.eureka]": DEBUG
    "[org.springframework.cloud.gateway.discovery]": DEBUG
