spring:
  application:
    name: api-gateway
  cloud:
    gateway:
    loadbalancer:
      ribbon:
        enabled: false
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://discovery-service:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:api-gateway}
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    securePortEnabled: false
    nonSecurePortEnabled: true
    preferIpAddress: false
    statusPageUrl: http://${eureka.instance.hostname}:8080/actuator/info
    healthCheckUrl: http://${eureka.instance.hostname}:8080/actuator/health
    homePageUrl: http://${eureka.instance.hostname}:8080/

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    gateway:
      access: UNRESTRICTED

logging:
  level:
    "[org.springframework.cloud.gateway]": DEBUG
    "[reactor.netty]": DEBUG
