spring.application.name=subscription-service
server.port=8087

# Eureka Client Configuration
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://discovery-service:8761/eureka}
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:subscription-service}
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}
eureka.instance.securePortEnabled=true
eureka.instance.securePort=${EUREKA_INSTANCE_SECURE_PORT:443}
eureka.instance.nonSecurePortEnabled=false
eureka.instance.preferIpAddress=false
eureka.instance.statusPageUrl=https://${eureka.instance.hostname}/actuator/info
eureka.instance.healthCheckUrl=https://${eureka.instance.hostname}/actuator/health
eureka.instance.homePageUrl=https://${eureka.instance.hostname}/

# Spring DataSource Configuration
spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/ayni?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Spring Data JPA Configuration
spring.jpa.show-sql=true

#Spring Data JPA Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.naming.physical-strategy=com.hidrogreen.subscription_service.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy

# RabbitMQ Configuration
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

# External Services Configuration
app.services.user-service.url=${USER_SERVICE_URL:http://user-service:8081}

# Elements take their values from maven pom.xml build-related information
documentation.application.description=@project.description@
documentation.application.version=@project.version@

# Actuator Configuration
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always