# Common Configuration - Payment Gateway Service
spring.application.name=hidrogreen-payment-gateway
server.port=8086

# Default profile for development (Docker)
spring.profiles.active=docker

# Configuration import
spring.config.import=secret.properties

# PayPal Configuration
paypal.mode=sandbox

# Actuator Configuration
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

documentation.application.description=Demo project for Spring Boot
documentation.application.version=0.0.1-SNAPSHOT
