spring.application.name=discovery-service
server.port=8761

eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:localhost}
eureka.instance.secure-port=${EUREKA_INSTANCE_SECURE_PORT:443}
eureka.instance.secure-port-enabled=true


eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/
