spring.application.name=discovery-service
server.port=8761

# Eureka Environment and Data Center Configuration
eureka.environment=${EUREKA_ENVIRONMENT:test}
eureka.datacenter=${EUREKA_DATACENTER:default}

eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:discovery-service}
eureka.instance.secure-port=${EUREKA_INSTANCE_SECURE_PORT:443}
eureka.instance.secure-port-enabled=true
eureka.instance.non-secure-port-enabled=false
eureka.instance.status-page-url=https://${eureka.instance.hostname}/actuator/info
eureka.instance.health-check-url=https://${eureka.instance.hostname}/actuator/health
eureka.instance.home-page-url=https://${eureka.instance.hostname}/

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=https://${eureka.instance.hostname}/eureka/

# Configuración de eviction para eliminar instancias inactivas
eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=10000
eureka.server.renewal-threshold-update-interval-ms=10000
eureka.server.renewal-percent-threshold=0.85

# Configuración de heartbeat y timeout
eureka.instance.lease-renewal-interval-in-seconds=30
eureka.instance.lease-expiration-duration-in-seconds=90
eureka.instance.health-check-interval-in-seconds=30

# Configuración de limpieza de registros
eureka.server.cleanup-interval-ms=10000
eureka.server.response-cache-update-interval-ms=3000

# Actuator Configuration
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
