spring.application.name=hidrogreen-payment-gateway

spring.config.import=secret.properties

server.port=8086

# paypal.client.id=${paypal.client.id}
# paypal.client.secret=${paypal.client.secret}

paypal.client.id=AefzW44y1ohudJ2Ft7EdBn9OXsl5N6M4qE-UuBcLSSR-IAVunKdsIzuPRaWf4KZqbOmHfBmt0q5VAAqF
paypal.client.secret=EP_gY9aMRTzNYykoVE1RxYKqW_jPuDfyBGNW9MtmfBwxjywW0SE_BtEEc2G7VeP2VIAgMFaGBw5PkwFp

app.url=http://localhost:8086

documentation.application.description=@project.description@
documentation.application.version=@project.version@


paypal.mode=sandbox
