spring.application.name=hidrogreen-payment-gateway

spring.config.import=secret.properties

server.port=8086

# paypal.client.id=${paypal.client.id}
# paypal.client.secret=${paypal.client.secret}

paypal.client.id=AefzW44y1ohudJ2Ft7EdBn9OXsl5N6M4qE-UuBcLSSR-IAVunKdsIzuPRaWf4KZqbOmHfBmt0q5VAAqF
paypal.client.secret=EP_gY9aMRTzNYykoVE1RxYKqW_jPuDfyBGNW9MtmfBwxjywW0SE_BtEEc2G7VeP2VIAgMFaGBw5PkwFp

paypal.mode=sandbox

app.url=http://localhost:8086


# Eureka Client Configuration
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://discovery-service:8761/eureka}
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:payment-gateway-service}
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}
eureka.instance.securePortEnabled=true
eureka.instance.securePort=${EUREKA_INSTANCE_SECURE_PORT:443}
eureka.instance.nonSecurePortEnabled=false
eureka.instance.preferIpAddress=false
eureka.instance.statusPageUrl=https://${eureka.instance.hostname}/actuator/info
eureka.instance.healthCheckUrl=https://${eureka.instance.hostname}/actuator/health
eureka.instance.homePageUrl=https://${eureka.instance.hostname}/

# Actuator Configuration
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always


documentation.application.description=@project.description@
documentation.application.version=@project.version@

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
