spring.application.name=hidrogreen-payment-gateway-service

spring.config.import=secret.properties

#paypal.client.id=${paypal.client.id}
#paypal.client.secret=${paypal.client.secret}

server.port=8088

paypal.client.id=${paypal.client.id}
paypal.client.secret=${paypal.client.secret}
app.url=http://localhost:8088


paypal.mode=sandbox
